// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhHC6H-LIWhNhV8b7AzUwkReCsR5u6qyg',
    appId: '1:326953281381:web:e40da313acbc4da15b638c',
    messagingSenderId: '326953281381',
    projectId: 'myschool-5e704',
    authDomain: 'myschool-5e704.firebaseapp.com',
    storageBucket: 'myschool-5e704.firebasestorage.app',
    measurementId: 'G-V2S5GDFR63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM42LUaGrcDnWruL7YPgaMs7WRzc9PWWo',
    appId: '1:326953281381:android:40b582a33a8142a25b638c',
    messagingSenderId: '326953281381',
    projectId: 'myschool-5e704',
    storageBucket: 'myschool-5e704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmm8RivDmIxSBMNx4LMgc7SgPl1q3NXY',
    appId: '1:326953281381:ios:b5eb9d0fcac227935b638c',
    messagingSenderId: '326953281381',
    projectId: 'myschool-5e704',
    storageBucket: 'myschool-5e704.firebasestorage.app',
    iosBundleId: 'com.example.mySchoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJmm8RivDmIxSBMNx4LMgc7SgPl1q3NXY',
    appId: '1:326953281381:ios:b5eb9d0fcac227935b638c',
    messagingSenderId: '326953281381',
    projectId: 'myschool-5e704',
    storageBucket: 'myschool-5e704.firebasestorage.app',
    iosBundleId: 'com.example.mySchoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhHC6H-LIWhNhV8b7AzUwkReCsR5u6qyg',
    appId: '1:326953281381:web:e0f78daeef2025a65b638c',
    messagingSenderId: '326953281381',
    projectId: 'myschool-5e704',
    authDomain: 'myschool-5e704.firebaseapp.com',
    storageBucket: 'myschool-5e704.firebasestorage.app',
    measurementId: 'G-BSJD2328LE',
  );
}
